### ISSUE TITLE
SASS?

### ISSUE THREAD

**Issue by unknownterritory** [kidwm/brackets-response#12]
This is an exciting extension. However, it would be even greater if it was compatible with SASS. Is it in your plans? :-)

**Comment by kidwm** [comment]
Sure, since now Brackets supports both SASS and LESS out of the box.

**Comment by unknownterritory** [comment]
Thanks! I'll be looking forward for it :-)

**Comment by ikbenben** [comment]
Hi asenseofdesign

I've duplicated this issue in the original repository at https://github.com/brimelow/Response-for-Brackets/issues/42 and provided some feedback
