### ISSUE TITLE
Some bugs

### ISSUE THREAD

**Issue by ghost** [kidwm/brackets-response#16]
Well sorry that I'm not (currently) too big when it comes to JS so I couldn't help out with a pull request, but from 0.44 [some things](http://puu.sh/csnve/72ba988590.png) seem a [bit off](http://puu.sh/csnvI/d4aa1ca586.png) -- and the dropdown opens only when LClick is held, then doesn't disappear as you can see from the first picture. 

To add to that I've found out that quick edit doesn't always work -- in the case when you don't have any rules/styles applied to the selected element.

Also the generated "media-queries.css" file gets wiped on every start of the responsive mode, even if it had queries already present from a previous edit, and it gets created in the root folder. So you might consider looking through the project folders for .css files later on, after you've dealt with the wiping.

Thank you for your time.

**Comment by anephew** [comment]
I didn't use an extension and forgot about these bugs. Same bugs here, confirm.

1) Dropdown problem
2) Yes
3) Same here. And this is a big bug

Need correction. Sadly the author stopped supporting this extension. And a new author has no time for support. I'll try to help but we need more people.

**Comment by ghost** [comment]
I'm pretty sure adobe will probably pick it up (the original author) as brackets comes closer to v1.0 or some time after that, in the mean time to fix the first problem you can just hide the whole dropdown completely (from the css file in the extension) and I'll be looking over the code for the 2nd and 3rd fix.

**Comment by ikbenben** [comment]
this should be working now in the original repository. the extension is called "Response for Brackets - original" in the extension manager. Install that instead of the one uploaded by kidwm

**Comment by ghost** [comment]
Thanks for the update.
