### ISSUE TITLE
I can't get it to work on Mac OS X 10.9.4

### ISSUE THREAD

**Issue by larz0** [kidwm/brackets-response#2]
I have an html file open and clicking on the Response for Brackets icon or hitting CMD+2 won't bring up the preview.

Thanks for updating the Brackets version number by the way.

**Comment by kidwm** [comment]
Can you post the Error output in console here?

Press F12 would show the Developer Tools in Google Chrome.

**Comment by larz0** [comment]
Here you go: 

![screen shot 2014-09-25 at 10 17 33 am](https://cloud.githubusercontent.com/assets/1495261/4408937/9731edbe-44d8-11e4-949a-20ab0c719f83.png)

**Comment by kidwm** [comment]
Did you install extension which hide the sidebar or area of Working Files?
Can you also list all extensions you installed?

**Comment by Idloj** [comment]
I have no other extensions installed, and it doesn't work for me, too.

**Comment by kidwm** [comment]
@Idloj could you also upload your error log?

**Comment by Idloj** [comment]
![screenshot from 2014-10-02 22 50 33](https://cloud.githubusercontent.com/assets/8083458/4497341/fccabc06-4a6d-11e4-9ad4-88e0d3f1a0b7.png)

**Comment by kidwm** [comment]
@Idloj How did you install this extension?
It seemed that your extension folder has no write permission.

I'll release a small update ASAP, hope that will solve your problem.

**Comment by Idloj** [comment]
Through the extension manager, and it does add the button and the menu items related. My extensions folder does have a write permission(just for myself and my group but I think it's sufficient).
BTW, I'm using Linux(Ubuntu 14.4) if you didn't notice by the path.

**Comment by kidwm** [comment]
@Idloj But the title of this issue is about Mac OS X :stuck_out_tongue_winking_eye: 

I've updated the extension, could you guys try this and see if it works?

**Comment by larz0** [comment]
Ok the new version loads, just that the buttons don't respond to click. I'm on Brackets Sprint 44.

I'll test it more this weekend or something.

![screen shot 2014-10-03 at 10 26 32 am](https://cloud.githubusercontent.com/assets/1495261/4509645/82f47d30-4b22-11e4-870e-3714239dc29d.png)

**Comment by Idloj** [comment]
Not working, doesn't output anything.

**Comment by larz0** [comment]
@kidwm the latest update worked. Thanks! Closing.
