### ISSUE TITLE
Brackets 1.0 php+html not working

### ISSUE THREAD

**Issue by tcanani** [kidwm/brackets-response#21]
Hi,

I'm using php with html code, as i'm working with wordpress and opencart and other platforms, and i couldn't make the live code to work with .php files. 

It just shows the code itself. I'm new to brackets so i don't know if i'm doing something wrong, or the extension isn't working with .php files? If not working, do you have plans for updating the extension so it can work with .php? I'm just loving brackets and this features is the best, so i'm really expecting it to work so i can move once and for all to brackets and continue my projects in it.

Thanks guys!

**Comment by kidwm** [comment]
Ref. #3

**Comment by kidwm** [comment]
You can run a php server to do it, see Set Preview URL section in README.
