### ISSUE TITLE
Option to set adress instead of it loading the current page in editor

### ISSUE THREAD

**Issue by jesperbjerke** [kidwm/brackets-response#3]
Since I work with Wordpress in 9 cases out of 10, this tool wont work for me cause I'm working with php mixed with html. Maybe get the URL from the Live Preview mode setting for the project?

**Comment by kidwm** [comment]
Hey, I didn't know that Live Preview can run with PHP ?!

I'll try to make the URL configurable.

**Comment by jesperbjerke** [comment]
It doesnt, what i know of, just figured you could reuse that setting :)
